services:
  redis:
    image: "redis:alpine"
    networks:
      - medihelp-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - medihelp-network

  ocr_worker:
    build:
      context: .
      dockerfile: ocr_worker/Dockerfile
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - medihelp-network

networks:
  medihelp-network: